FROM rouhim/steamcmd-wine:latest

# Install additional dependencies
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    jq ncat && \
    rm -rf /var/lib/apt/lists/*

USER $USER

ENV STEAM_APP_ID="2465200"
ENV STARTUP_COMMAND="sh $USER_HOME/server.sh"

COPY pre.sh $USER_HOME/pre.sh
COPY server.sh $USER_HOME/server.sh
COPY accessibility-test.sh $USER_HOME/accessibility-test.sh
